version: "3.1"

services:
  test-postgres:
    container_name: postgres
    env_file: docker/.env
    image: postgres:13.2
    ports:
      - "5432:5432"
    volumes:
      - ./docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

