#!/bin/bash
set -e

export PGPASSWORD="$POSTGRES_PASSWORD"
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE USER $TEST_USER WITH PASSWORD '$TEST_PASSWORD';
  GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $TEST_USER;
  SELECT datname FROM pg_database;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" -d "$POSTGRES_DB" <<-EOSQL
   GRANT ALL ON SCHEMA public TO $TEST_USER;
EOSQL