spring:
  datasource:
    username: developer
    password: password
    url: jdbc:postgresql://localhost:5432/shopping_app
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
server:
  port: 8083